#!/bin/sh
set -e 
if cd ssa/ssa-1.0; then git pull; else git clone https://github.com/Usable-Security-and-Privacy-Lab/ssa.git; fi
cd ssa-1.0/src
make 
sudo cp ssa.ko /lib/modules/`uname -r`
sudo depmod -a
sudo modprobe ssa
sudo sh -c "printf \"#Load ssa.ko at boot\nssa\" > /etc/modules-load.d/ssa.conf"
cd ..

sudo sh -c "printf \"[Unit]\nAfter=network-online.target\n\n[Service]\nExecStart=/bin/bash -c 'cd /usr/src/ssa-daemon && PATH=/usr/src/ssa-daemon:$PATH exec ./ssa_daemon'\n\n[Install]\nWantedBy=network-online.target\n\n\" > /etc/systemd/system/ssa-daemon.service"
sudo systemctl daemon-reload
sudo systemctl enable ssa-daemon.service
sudo systemctl start ssa-daemon.service
#DKMS support
sudo dkms add -m ssa -v 1.0
sudo dkms build -m ssa -v 1.0 && sudo dkms install -m ssa -v 1.0 || true
#Cleanup(do last)
# sudo rm -r ssa # moved to prerm for DKMS support.
#DEBHELPER#
exit 0
